[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hsanchez/colabs/blob/main/lstm/lstm-for-signal.ipynb)

## LSTM for SIGNAL

In [308]:
import pandas as pd

# data_file = https://raw.githubusercontent.com/hsanchez/colabs/main/lstm/synthetic_email_data.csv
df = pd.read_csv("synthetic_email_data.csv", index_col="created_at")
df.head()

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39        8.32   
2021-09-01 00:02:00+00:00               23.02        8.93   
2021-09-01 00:04:00+00:00               25.49       10.10   
2021-09-01 00:06:00+00:00               25.22        9.24   
2021-09-01 00:08:00+00:00               23.16        9.02   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                  5.37            5.37   
2021-09-01 00:02:00+00:00                  5.95            5.95   
2021-09-01 00:04:00+00:00                  5.84            5.84   
2021-09-01 00:06:00+00:00                  7.07            7.07   
2021-09-01 00:08:00+00:00                  5.18            5.18   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00           4.79        7.57                  7.57   
2021-09-01 00:02:00+00:00           4.60        8.50                  8.50   
2021-09-01 00:04:00+00:00           5.70        8.07                  8.07   
2021-09-01 00:06:00+00:00           5.18        8.66                  8.66   
2021-09-01 00:08:00+00:00           5.29        7.98                  7.98   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00               7.60  
2021-09-01 00:02:00+00:00               7.78  
2021-09-01 00:04:00+00:00               7.64  
2021-09-01 00:06:00+00:00               7.69  
2021-09-01 00:08:00+00:00               7.74

Change persuasion values at random, and values are in _{0, 1, 2, 3}_

In [309]:
import numpy as np

persuasion_map = {'credibility_appeal': 0, 'logical_appeal': 1, 'task_specific': 2, 'unknown': 3}

data = np.random.randint(0, 3, size=36720)
data, len(data)

(array([2, 0, 0, ..., 0, 2, 1]), 36720)

**Columns** represent sender, email, and patch information and **rows** represent (sorted) timestamps of features.

In [310]:
df_updated_persuasion = pd.DataFrame(data, columns=['persuasion'])
df['persuasion'] = df_updated_persuasion['persuasion'].to_numpy()
df.head()

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                  5.37            5.37   
2021-09-01 00:02:00+00:00                  5.95            5.95   
2021-09-01 00:04:00+00:00                  5.84            5.84   
2021-09-01 00:06:00+00:00                  7.07            7.07   
2021-09-01 00:08:00+00:00                  5.18            5.18   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00           4.79        7.57                  7.57   
2021-09-01 00:02:00+00:00           4.60        8.50                  8.50   
2021-09-01 00:04:00+00:00           5.70        8.07                  8.07   
2021-09-01 00:06:00+00:00           5.18        8.66                  8.66   
2021-09-01 00:08:00+00:00           5.29        7.98                  7.98   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00               7.60  
2021-09-01 00:02:00+00:00               7.78  
2021-09-01 00:04:00+00:00               7.64  
2021-09-01 00:06:00+00:00               7.69  
2021-09-01 00:08:00+00:00               7.74

Change 'number_of_recipients' values at random, and values are in _{1, 2, 3, ..., 18}_

In [311]:
# random values between 1 and 18 for emails' number of recipients
data_recipients = np.random.uniform(1.0, 18.0, 36720).astype("int")
df_updated_recipients = pd.DataFrame(data_recipients, columns=['number_of_recipients'])
df_updated_recipients.head()

number_of_recipients
0                    11
1                    10
2                     5
3                    12
4                     2

In [312]:
x = df_updated_recipients["number_of_recipients"].to_numpy()
y = df["number_of_recipients"].to_numpy()

df["number_of_recipients"] = x
df.head()


message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11            5.37   
2021-09-01 00:02:00+00:00                    10            5.95   
2021-09-01 00:04:00+00:00                     5            5.84   
2021-09-01 00:06:00+00:00                    12            7.07   
2021-09-01 00:08:00+00:00                     2            5.18   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00           4.79        7.57                  7.57   
2021-09-01 00:02:00+00:00           4.60        8.50                  8.50   
2021-09-01 00:04:00+00:00           5.70        8.07                  8.07   
2021-09-01 00:06:00+00:00           5.18        8.66                  8.66   
2021-09-01 00:08:00+00:00           5.29        7.98                  7.98   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00               7.60  
2021-09-01 00:02:00+00:00               7.78  
2021-09-01 00:04:00+00:00               7.64  
2021-09-01 00:06:00+00:00               7.69  
2021-09-01 00:08:00+00:00               7.74

In [313]:
columns_of_interest = ['is_first_email', 'is_last_email', 'is_verbose', 'is_replied_within_30', 'is_accepted_patch']
for each_column in columns_of_interest:
  df[each_column] = np.random.randint(2, size=36720)

df.head()

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11               1   
2021-09-01 00:02:00+00:00                    10               1   
2021-09-01 00:04:00+00:00                     5               1   
2021-09-01 00:06:00+00:00                    12               0   
2021-09-01 00:08:00+00:00                     2               0   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00              1           0                     0   
2021-09-01 00:02:00+00:00              1           1                     0   
2021-09-01 00:04:00+00:00              1           0                     0   
2021-09-01 00:06:00+00:00              0           0                     0   
2021-09-01 00:08:00+00:00              0           1                     1   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00                  0  
2021-09-01 00:02:00+00:00                  0  
2021-09-01 00:04:00+00:00                  1  
2021-09-01 00:06:00+00:00                  1  
2021-09-01 00:08:00+00:00                  0

In [314]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36720 entries, 2021-09-01 00:00:00+00:00 to 2021-10-21 23:58:00+00:00
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   message_experience    36720 non-null  float64
 1   persuasion            36720 non-null  int64  
 2   number_of_recipients  36720 non-null  int64  
 3   is_first_email        36720 non-null  int64  
 4   is_last_email         36720 non-null  int64  
 5   is_verbose            36720 non-null  int64  
 6   is_replied_within_30  36720 non-null  int64  
 7   is_accepted_patch     36720 non-null  int64  
dtypes: float64(1), int64(7)
memory usage: 2.5+ MB


In [315]:
df

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   
...                                       ...         ...   
2021-10-21 23:50:00+00:00                2.58           0   
2021-10-21 23:52:00+00:00                3.02           0   
2021-10-21 23:54:00+00:00                2.37           0   
2021-10-21 23:56:00+00:00                3.07           2   
2021-10-21 23:58:00+00:00                2.88           1   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11               1   
2021-09-01 00:02:00+00:00                    10               1   
2021-09-01 00:04:00+00:00                     5               1   
2021-09-01 00:06:00+00:00                    12               0   
2021-09-01 00:08:00+00:00                     2               0   
...                                         ...             ...   
2021-10-21 23:50:00+00:00                    11               1   
2021-10-21 23:52:00+00:00                     8               0   
2021-10-21 23:54:00+00:00                    12               1   
2021-10-21 23:56:00+00:00                     9               0   
2021-10-21 23:58:00+00:00                     2               1   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00              1           0                     0   
2021-09-01 00:02:00+00:00              1           1                     0   
2021-09-01 00:04:00+00:00              1           0                     0   
2021-09-01 00:06:00+00:00              0           0                     0   
2021-09-01 00:08:00+00:00              0           1                     1   
...                                  ...         ...                   ...   
2021-10-21 23:50:00+00:00              1           1                     1   
2021-10-21 23:52:00+00:00              1           0                     0   
2021-10-21 23:54:00+00:00              1           0                     1   
2021-10-21 23:56:00+00:00              1           0                     0   
2021-10-21 23:58:00+00:00              0           1                     0   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00                  0  
2021-09-01 00:02:00+00:00                  0  
2021-09-01 00:04:00+00:00                  1  
2021-09-01 00:06:00+00:00                  1  
2021-09-01 00:08:00+00:00                  0  
...                                      ...  
2021-10-21 23:50:00+00:00                  0  
2021-10-21 23:52:00+00:00                  1  
2021-10-21 23:54:00+00:00                  1  
2021-10-21 23:56:00+00:00                  0  
2021-10-21 23:58:00+00:00                  1  

[36720 rows x 8 columns]

# Create the target variable

For our forecasting target, we need to shift the Austin sensor's column forward in time. Let's forecast 30 minutes in the future, which is 15 two-minute periods. The newly created target column won't have values in the final 15 rows, so we'll drop those.

In [316]:
# Create the target variable
target_feature = "is_replied_within_30"
features = list(df.columns.difference([target_feature]))
features

['is_accepted_patch',
 'is_first_email',
 'is_last_email',
 'is_verbose',
 'message_experience',
 'number_of_recipients',
 'persuasion']

In [317]:
# forecast 30 minutes in the future, which is 15 two-minute periods.
forecast_lead = 15
# The newly created target column won't have values in 
# the final 15 rows, so we'll drop those.
# Here we are shifting the Austin sensor's column forward in time
shifted_in_future = df[target_feature].shift(-forecast_lead)
shifted_in_future

created_at
2021-09-01 00:00:00+00:00    0.0
2021-09-01 00:02:00+00:00    1.0
2021-09-01 00:04:00+00:00    0.0
2021-09-01 00:06:00+00:00    0.0
2021-09-01 00:08:00+00:00    0.0
                            ... 
2021-10-21 23:50:00+00:00    NaN
2021-10-21 23:52:00+00:00    NaN
2021-10-21 23:54:00+00:00    NaN
2021-10-21 23:56:00+00:00    NaN
2021-10-21 23:58:00+00:00    NaN
Name: is_replied_within_30, Length: 36720, dtype: float64

In [318]:
shifted_in_future = shifted_in_future.to_numpy()
shifted_in_future

array([ 0.,  1.,  0., ..., nan, nan, nan])

In [319]:
df_copy = df.copy()
df_copy

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   
...                                       ...         ...   
2021-10-21 23:50:00+00:00                2.58           0   
2021-10-21 23:52:00+00:00                3.02           0   
2021-10-21 23:54:00+00:00                2.37           0   
2021-10-21 23:56:00+00:00                3.07           2   
2021-10-21 23:58:00+00:00                2.88           1   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11               1   
2021-09-01 00:02:00+00:00                    10               1   
2021-09-01 00:04:00+00:00                     5               1   
2021-09-01 00:06:00+00:00                    12               0   
2021-09-01 00:08:00+00:00                     2               0   
...                                         ...             ...   
2021-10-21 23:50:00+00:00                    11               1   
2021-10-21 23:52:00+00:00                     8               0   
2021-10-21 23:54:00+00:00                    12               1   
2021-10-21 23:56:00+00:00                     9               0   
2021-10-21 23:58:00+00:00                     2               1   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00              1           0                     0   
2021-09-01 00:02:00+00:00              1           1                     0   
2021-09-01 00:04:00+00:00              1           0                     0   
2021-09-01 00:06:00+00:00              0           0                     0   
2021-09-01 00:08:00+00:00              0           1                     1   
...                                  ...         ...                   ...   
2021-10-21 23:50:00+00:00              1           1                     1   
2021-10-21 23:52:00+00:00              1           0                     0   
2021-10-21 23:54:00+00:00              1           0                     1   
2021-10-21 23:56:00+00:00              1           0                     0   
2021-10-21 23:58:00+00:00              0           1                     0   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00                  0  
2021-09-01 00:02:00+00:00                  0  
2021-09-01 00:04:00+00:00                  1  
2021-09-01 00:06:00+00:00                  1  
2021-09-01 00:08:00+00:00                  0  
...                                      ...  
2021-10-21 23:50:00+00:00                  0  
2021-10-21 23:52:00+00:00                  1  
2021-10-21 23:54:00+00:00                  1  
2021-10-21 23:56:00+00:00                  0  
2021-10-21 23:58:00+00:00                  1  

[36720 rows x 8 columns]

In [320]:
# The newly created target column won't have values in 
# the final 15 rows, so we'll drop those.
# Here we are shifting the Austin sensor's column forward in time
df_copy[target_feature] = shifted_in_future
# df_copy = df_copy.iloc[:-forecast_lead]
# df_copy
df_copy

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   
...                                       ...         ...   
2021-10-21 23:50:00+00:00                2.58           0   
2021-10-21 23:52:00+00:00                3.02           0   
2021-10-21 23:54:00+00:00                2.37           0   
2021-10-21 23:56:00+00:00                3.07           2   
2021-10-21 23:58:00+00:00                2.88           1   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11               1   
2021-09-01 00:02:00+00:00                    10               1   
2021-09-01 00:04:00+00:00                     5               1   
2021-09-01 00:06:00+00:00                    12               0   
2021-09-01 00:08:00+00:00                     2               0   
...                                         ...             ...   
2021-10-21 23:50:00+00:00                    11               1   
2021-10-21 23:52:00+00:00                     8               0   
2021-10-21 23:54:00+00:00                    12               1   
2021-10-21 23:56:00+00:00                     9               0   
2021-10-21 23:58:00+00:00                     2               1   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00              1           0                   0.0   
2021-09-01 00:02:00+00:00              1           1                   1.0   
2021-09-01 00:04:00+00:00              1           0                   0.0   
2021-09-01 00:06:00+00:00              0           0                   0.0   
2021-09-01 00:08:00+00:00              0           1                   0.0   
...                                  ...         ...                   ...   
2021-10-21 23:50:00+00:00              1           1                   NaN   
2021-10-21 23:52:00+00:00              1           0                   NaN   
2021-10-21 23:54:00+00:00              1           0                   NaN   
2021-10-21 23:56:00+00:00              1           0                   NaN   
2021-10-21 23:58:00+00:00              0           1                   NaN   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00                  0  
2021-09-01 00:02:00+00:00                  0  
2021-09-01 00:04:00+00:00                  1  
2021-09-01 00:06:00+00:00                  1  
2021-09-01 00:08:00+00:00                  0  
...                                      ...  
2021-10-21 23:50:00+00:00                  0  
2021-10-21 23:52:00+00:00                  1  
2021-10-21 23:54:00+00:00                  1  
2021-10-21 23:56:00+00:00                  0  
2021-10-21 23:58:00+00:00                  1  

[36720 rows x 8 columns]

In [321]:
df_copy = df_copy.iloc[:-forecast_lead]
df_copy

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   
...                                       ...         ...   
2021-10-21 23:20:00+00:00                2.64           0   
2021-10-21 23:22:00+00:00                2.79           1   
2021-10-21 23:24:00+00:00                2.10           0   
2021-10-21 23:26:00+00:00                2.55           0   
2021-10-21 23:28:00+00:00                2.47           2   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11               1   
2021-09-01 00:02:00+00:00                    10               1   
2021-09-01 00:04:00+00:00                     5               1   
2021-09-01 00:06:00+00:00                    12               0   
2021-09-01 00:08:00+00:00                     2               0   
...                                         ...             ...   
2021-10-21 23:20:00+00:00                    12               1   
2021-10-21 23:22:00+00:00                    10               0   
2021-10-21 23:24:00+00:00                     2               0   
2021-10-21 23:26:00+00:00                     1               0   
2021-10-21 23:28:00+00:00                     3               0   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00              1           0                   0.0   
2021-09-01 00:02:00+00:00              1           1                   1.0   
2021-09-01 00:04:00+00:00              1           0                   0.0   
2021-09-01 00:06:00+00:00              0           0                   0.0   
2021-09-01 00:08:00+00:00              0           1                   0.0   
...                                  ...         ...                   ...   
2021-10-21 23:20:00+00:00              0           0                   1.0   
2021-10-21 23:22:00+00:00              0           0                   0.0   
2021-10-21 23:24:00+00:00              0           1                   1.0   
2021-10-21 23:26:00+00:00              0           0                   0.0   
2021-10-21 23:28:00+00:00              1           0                   0.0   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00                  0  
2021-09-01 00:02:00+00:00                  0  
2021-09-01 00:04:00+00:00                  1  
2021-09-01 00:06:00+00:00                  1  
2021-09-01 00:08:00+00:00                  0  
...                                      ...  
2021-10-21 23:20:00+00:00                  0  
2021-10-21 23:22:00+00:00                  0  
2021-10-21 23:24:00+00:00                  1  
2021-10-21 23:26:00+00:00                  1  
2021-10-21 23:28:00+00:00                  0  

[36705 rows x 8 columns]

In [322]:
df_copy[target_feature] = df_copy[target_feature].to_numpy().astype('int')
df_copy

/var/folders/v8/x9t6mgdn0rj2w01q3kpsqbdnd3n78t/T/ipykernel_77992/198812636.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   
...                                       ...         ...   
2021-10-21 23:20:00+00:00                2.64           0   
2021-10-21 23:22:00+00:00                2.79           1   
2021-10-21 23:24:00+00:00                2.10           0   
2021-10-21 23:26:00+00:00                2.55           0   
2021-10-21 23:28:00+00:00                2.47           2   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11               1   
2021-09-01 00:02:00+00:00                    10               1   
2021-09-01 00:04:00+00:00                     5               1   
2021-09-01 00:06:00+00:00                    12               0   
2021-09-01 00:08:00+00:00                     2               0   
...                                         ...             ...   
2021-10-21 23:20:00+00:00                    12               1   
2021-10-21 23:22:00+00:00                    10               0   
2021-10-21 23:24:00+00:00                     2               0   
2021-10-21 23:26:00+00:00                     1               0   
2021-10-21 23:28:00+00:00                     3               0   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00              1           0                     0   
2021-09-01 00:02:00+00:00              1           1                     1   
2021-09-01 00:04:00+00:00              1           0                     0   
2021-09-01 00:06:00+00:00              0           0                     0   
2021-09-01 00:08:00+00:00              0           1                     0   
...                                  ...         ...                   ...   
2021-10-21 23:20:00+00:00              0           0                     1   
2021-10-21 23:22:00+00:00              0           0                     0   
2021-10-21 23:24:00+00:00              0           1                     1   
2021-10-21 23:26:00+00:00              0           0                     0   
2021-10-21 23:28:00+00:00              1           0                     0   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00                  0  
2021-09-01 00:02:00+00:00                  0  
2021-09-01 00:04:00+00:00                  1  
2021-09-01 00:06:00+00:00                  1  
2021-09-01 00:08:00+00:00                  0  
...                                      ...  
2021-10-21 23:20:00+00:00                  0  
2021-10-21 23:22:00+00:00                  0  
2021-10-21 23:24:00+00:00                  1  
2021-10-21 23:26:00+00:00                  1  
2021-10-21 23:28:00+00:00                  0  

[36705 rows x 8 columns]

# Create a hold-out test set and preprocess the data

As always, we need a test set to evaluate our model. Here, we'll keep it simple with a single temporal split, i.e. our test set is the last 11 days of data (about 23% of the total). 

In [323]:
# Create a hold out set
test_start = "2021-10-10"

df_train = df_copy.loc[:test_start].copy()
df_test = df_copy.loc[test_start:].copy()

print(df_train.head())
print("==========")
print(df_test.head())

                           message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00               23.39           2   
2021-09-01 00:02:00+00:00               23.02           0   
2021-09-01 00:04:00+00:00               25.49           0   
2021-09-01 00:06:00+00:00               25.22           0   
2021-09-01 00:08:00+00:00               23.16           0   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00                    11               1   
2021-09-01 00:02:00+00:00                    10               1   
2021-09-01 00:04:00+00:00                     5               1   
2021-09-01 00:06:00+00:00                    12               0   
2021-09-01 00:08:00+00:00                     2               0   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at              

In [280]:
print("Test set fraction:", len(df_test) / len(df))

Test set fraction: 0.23488562091503268


# Standardize the features and target

In my experience, standardizing both the features and the target seems to help substantially.

In [324]:
# Standardize the features and target, based on the training set
target_mean = df_train[target_feature].mean()
target_stdev = df_train[target_feature].std()

print(target_mean)
print("==========")
print(target_stdev)

0.49729344729344727
0.5000015777600486


In [325]:
for c in df_train.columns:
    if c not in ['number_of_recipients', 'message_experience']:
        continue
    mean = df_train[c].mean()
    stdev = df_train[c].std()

    df_train[c] = (df_train[c] - mean) / stdev
    df_test[c] = (df_test[c] - mean) / stdev

In [326]:
df_train

message_experience  persuasion  \
created_at                                                  
2021-09-01 00:00:00+00:00            1.105852           2   
2021-09-01 00:02:00+00:00            1.064701           0   
2021-09-01 00:04:00+00:00            1.339408           0   
2021-09-01 00:06:00+00:00            1.309379           0   
2021-09-01 00:08:00+00:00            1.080272           0   
...                                       ...         ...   
2021-10-09 23:50:00+00:00           -0.460086           0   
2021-10-09 23:52:00+00:00           -0.532377           0   
2021-10-09 23:54:00+00:00           -0.435618           2   
2021-10-09 23:56:00+00:00           -0.484554           0   
2021-10-09 23:58:00+00:00           -0.456750           1   

                           number_of_recipients  is_first_email  \
created_at                                                        
2021-09-01 00:00:00+00:00              0.406214               1   
2021-09-01 00:02:00+00:00              0.201477               1   
2021-09-01 00:04:00+00:00             -0.822205               1   
2021-09-01 00:06:00+00:00              0.610950               0   
2021-09-01 00:08:00+00:00             -1.436414               0   
...                                         ...             ...   
2021-10-09 23:50:00+00:00             -0.822205               1   
2021-10-09 23:52:00+00:00              0.815686               1   
2021-10-09 23:54:00+00:00             -1.231677               1   
2021-10-09 23:56:00+00:00             -0.412732               1   
2021-10-09 23:58:00+00:00              0.406214               0   

                           is_last_email  is_verbose  is_replied_within_30  \
created_at                                                                   
2021-09-01 00:00:00+00:00              1           0                     0   
2021-09-01 00:02:00+00:00              1           1                     1   
2021-09-01 00:04:00+00:00              1           0                     0   
2021-09-01 00:06:00+00:00              0           0                     0   
2021-09-01 00:08:00+00:00              0           1                     0   
...                                  ...         ...                   ...   
2021-10-09 23:50:00+00:00              0           1                     0   
2021-10-09 23:52:00+00:00              0           0                     1   
2021-10-09 23:54:00+00:00              0           0                     1   
2021-10-09 23:56:00+00:00              0           0                     1   
2021-10-09 23:58:00+00:00              0           1                     0   

                           is_accepted_patch  
created_at                                    
2021-09-01 00:00:00+00:00                  0  
2021-09-01 00:02:00+00:00                  0  
2021-09-01 00:04:00+00:00                  1  
2021-09-01 00:06:00+00:00                  1  
2021-09-01 00:08:00+00:00                  0  
...                                      ...  
2021-10-09 23:50:00+00:00                  0  
2021-10-09 23:52:00+00:00                  1  
2021-10-09 23:54:00+00:00                  1  
2021-10-09 23:56:00+00:00                  1  
2021-10-09 23:58:00+00:00                  0  

[28080 rows x 8 columns]

# Create datasets that PyTorch DataLoader can work with

Typically, time series regression tutorials lessons show how to create features by extracting parts of the timestamps or by lagging features, that is, using past values of each feature as features in their own right. That's not what we're going to do with the LSTM; **for each training instance, we're going to give the model a sequence of observations.**

One elegant way to do this is to **create a PyTorch Dataset class,** which is simpler than you might think. This strategy lets us lean on PyTorch's nice DataLoader class to keep the model training and evaluation code super clean.

Our custom Dataset just needs to specify what happens when somebody requests the i'th element of the dataset. In a tabular dataset, this would be the i'th row of the table, but here we need to retrieve a sequence of rows.

So, given **i** and the **sequence_length**, we return the block of data from **i - sequence_length** through row **i**. If i is at the beginning of the dataset, we pad by repeating the first row as many times as needed to make the output have sequence_length rows. The only trick is avoiding off-by-1 errors in the slicing and padding.

All the magic happens in the __getitem__ method in this snippet.

In [327]:
import torch
from torch.utils.data import Dataset

class SequenceDataset(Dataset):
    def __init__(self, dataframe, target, features, sequence_length=5):
        self.features = features
        self.target = target
        self.sequence_length = sequence_length
        self.y = torch.tensor(dataframe[self.target].values).float()
        self.X = torch.tensor(dataframe[self.features].values).float()

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, i): 
        if i >= self.sequence_length - 1:
            i_start = i - self.sequence_length + 1
            x = self.X[i_start:(i + 1), :]
        else:
            padding = self.X[0].repeat(self.sequence_length - i - 1, 1)
            x = self.X[0:(i + 1), :]
            x = torch.cat((padding, x), 0)

        return x, self.y[i]

Show this SequenceDataset in action

In [328]:
i = 27
sequence_length = 4

train_dataset = SequenceDataset(
    df_train,
    target=target_feature,
    features=features,
    sequence_length=sequence_length
)

X, y = train_dataset[i]
X

tensor([[ 1.0000,  1.0000,  0.0000,  0.0000,  1.7142, -0.4127,  1.0000],
        [ 1.0000,  0.0000,  1.0000,  0.0000,  1.7398, -0.4127,  2.0000],
        [ 1.0000,  0.0000,  1.0000,  1.0000,  1.4540, -0.2080,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  1.0000,  1.4973, -1.6411,  2.0000]])

Our output feature tensor has a column for each of the five input sensors, and a row for each of the four time steps in the sequence. The last row is row 27 of the original table.

If we take index 28 instead, we see the rows are shifted forward in time by 1 step. The oldest row is popped off the back and row 28 is pushed onto the front.

In [329]:
X, y = train_dataset[i + 1]
X, y

(tensor([[ 1.0000,  0.0000,  1.0000,  0.0000,  1.7398, -0.4127,  2.0000],
         [ 1.0000,  0.0000,  1.0000,  1.0000,  1.4540, -0.2080,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000,  1.4973, -1.6411,  2.0000],
         [ 1.0000,  1.0000,  0.0000,  0.0000,  1.8232, -1.0269,  2.0000]]),
 tensor(0.))

Just to confirm, here's the same logic for item 27, with Pandas DataFrame slicing.

In [330]:
print(df_train[features].iloc[(i - sequence_length + 1): (i + 1)])

                           is_accepted_patch  is_first_email  is_last_email  \
created_at                                                                    
2021-09-01 00:48:00+00:00                  1               1              0   
2021-09-01 00:50:00+00:00                  1               0              1   
2021-09-01 00:52:00+00:00                  1               0              1   
2021-09-01 00:54:00+00:00                  0               0              0   

                           is_verbose  message_experience  \
created_at                                                  
2021-09-01 00:48:00+00:00           0            1.714209   
2021-09-01 00:50:00+00:00           0            1.739789   
2021-09-01 00:52:00+00:00           1            1.453961   
2021-09-01 00:54:00+00:00           1            1.497336   

                           number_of_recipients  persuasion  
created_at                                                   
2021-09-01 00:48:00+00:00         

The next step is to set the dataset in a PyTorch DataLoader, which will draw minibatches of data for us. Let's try a small batch size of 3, to illustrate. The feature tensor returned by a call to our train_loader has shape 3 x 4 x 5, which reflects our data structure choices:

- 3: batch size
- 4: sequence length
- 5: number of features

In [331]:
from torch.utils.data import DataLoader
torch.manual_seed(99)

train_loader = DataLoader(train_dataset, batch_size=3, shuffle=True)

X, y = next(iter(train_loader))
print(X.shape)
print(X)

torch.Size([3, 4, 7])
tensor([[[ 0.0000,  1.0000,  1.0000,  0.0000, -0.0419, -1.6411,  0.0000],
         [ 0.0000,  0.0000,  1.0000,  1.0000, -0.0297, -0.2080,  1.0000],
         [ 0.0000,  1.0000,  0.0000,  0.0000, -0.1364,  1.0204,  2.0000],
         [ 0.0000,  1.0000,  1.0000,  1.0000, -0.1965, -0.4127,  2.0000]],

        [[ 1.0000,  0.0000,  0.0000,  1.0000, -1.1697,  1.0204,  2.0000],
         [ 0.0000,  0.0000,  1.0000,  1.0000, -1.1463,  1.4299,  0.0000],
         [ 1.0000,  1.0000,  0.0000,  0.0000, -1.1752, -0.8222,  0.0000],
         [ 1.0000,  1.0000,  0.0000,  1.0000, -1.0540, -1.0269,  1.0000]],

        [[ 1.0000,  0.0000,  0.0000,  1.0000,  0.1572, -1.6411,  0.0000],
         [ 0.0000,  1.0000,  0.0000,  0.0000,  0.4452, -0.8222,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  0.1594,  1.4299,  0.0000],
         [ 0.0000,  0.0000,  1.0000,  0.0000,  0.2595, -1.6411,  2.0000]]])


# Create the datasets and data loaders for real

Now let's do it for real, with a sequence of 30 time steps (60 minutes). For training, we'll shuffle the data (the rows within each data sequence are not shuffled, only the order in which we draw the blocks). For the test set, shuffling isn't necessary.

In [332]:
torch.manual_seed(101)

batch_size = 4
sequence_length = 30

train_dataset = SequenceDataset(
    df_train,
    target=target_feature,
    features=features,
    sequence_length=sequence_length
)

test_dataset = SequenceDataset(
    df_test,
    target=target_feature,
    features=features,
    sequence_length=sequence_length
)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

X, y = next(iter(train_loader))

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: torch.Size([4, 30, 7])
Target shape: torch.Size([4])


# The model and learning algorithm

With the hard data structure part done, now it's all downhill from here! A few notes to highlight in the ShallowRegressionLSTM model below:

- Most importantly, we have to keep track of which dimension represents the batch in our input tensors. As we just saw, our data loaders use the first dimension for this, but the PyTorch [LSTM layer](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html)'s default is to use the second dimension instead. So we set batch_first=True to make the dimensions line up, but confusingly, this doesn't apply to the hidden and cell state tensors. In the forward method, we initialize h0 and c0 with batch size as the second dimension.
- We'll hard code a single layer just to keep things simple.
- The output layer of the model is linear with a single output unit because we're doing regression. **This is one of only two lines of code that would need to change for a classification task.**

In [348]:
import torch
from torch import nn
import torch.nn.functional as F

class ShallowRegressionLSTM(nn.Module):
    def __init__(self, num_sensors, hidden_units):
        super().__init__()
        self.num_sensors = num_sensors  # this is the number of features
        self.hidden_units = hidden_units
        self.num_layers = 1

        self.lstm = nn.LSTM(
            input_size=num_sensors,
            hidden_size=hidden_units,
            batch_first=True,
            num_layers=self.num_layers
        )
        
        self.dropout = nn.Dropout(0.5)
        self.linear = nn.Linear(in_features=self.hidden_units, out_features=1)
        self.fc2 = nn.Linear(self.hidden_units * 2, 1)

    def forward(self, x):
        batch_size = x.shape[0]
        h0 = torch.zeros(self.num_layers, batch_size, self.hidden_units).requires_grad_()
        c0 = torch.zeros(self.num_layers, batch_size, self.hidden_units).requires_grad_()
        
        _, (hn, _) = self.lstm(x, (h0, c0))
        out = self.linear(hn[0]).flatten()  # First dim of Hn is num_layers, which is set to 1 above.
        out = self.dropout(out)
        # out = torch.relu_(self.linear(out[:,-1,:]))
		# # The last hidden state is taken
		# out = torch.relu_(out)
		# out = self.dropout(out)
        return F.sigmoid(out)

The other thing that would need to change is the loss function. Here we use the standard regression objective of mean square error, i.e. MSELoss.

I've chosen the learning rate and the number of hidden units by hand to get decent results with a model that trains relatively quickly on my laptop, but these would be great hyperparameters to experiment with more systematically.

In [349]:
learning_rate = 5e-5
num_hidden_units = 16

model = ShallowRegressionLSTM(num_sensors=len(features), hidden_units=num_hidden_units)
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Train

Time to get the ship underway! The train_model and test_model functions below are standard PyTorch boilerplate; there is nothing in them specific to LSTMs or time series data. But that's the point: by using a custom PyTorch Dataset and a DataLoader, we can use off-the-shelf training and evaluation loops.

In [350]:
def train_model(data_loader, model, loss_function, optimizer):
    num_batches = len(data_loader)
    total_loss = 0
    model.train()
    
    for X, y in data_loader:
        output = model(X)
        loss = loss_function(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / num_batches
    print(f"Train loss: {avg_loss}")

def test_model(data_loader, model, loss_function):
    
    num_batches = len(data_loader)
    total_loss = 0

    model.eval()
    with torch.no_grad():
        for X, y in data_loader:
            output = model(X)
            total_loss += loss_function(output, y).item()

    avg_loss = total_loss / num_batches
    print(f"Test loss: {avg_loss}")

In [351]:
print("Untrained test\n--------")
test_model(test_loader, model, loss_function)
print()

for ix_epoch in range(3):
    print(f"Epoch {ix_epoch}\n---------")
    train_model(train_loader, model, loss_function, optimizer=optimizer)
    test_model(test_loader, model, loss_function)
    print()

Untrained test
--------
tensor([0.5218, 0.5346, 0.5338, 0.5440])
tensor([0.5545, 0.5491, 0.5514, 0.5476])
tensor([0.5509, 0.5482, 0.5148, 0.5049])
tensor([0.4996, 0.5331, 0.5227, 0.5180])
tensor([0.5450, 0.5469, 0.5098, 0.5320])
tensor([0.5424, 0.5287, 0.5188, 0.5460])
tensor([0.5397, 0.5424, 0.5241, 0.5375])
tensor([0.5106, 0.5237, 0.5310, 0.5151])
tensor([0.5333, 0.5356, 0.5285, 0.5100])
tensor([0.5187, 0.5131, 0.5025, 0.5154])
tensor([0.5154, 0.5346, 0.5288, 0.5564])
tensor([0.5460, 0.5292, 0.5203, 0.5194])
tensor([0.5065, 0.5060, 0.5307, 0.5143])
tensor([0.5170, 0.5311, 0.5138, 0.5414])
tensor([0.5129, 0.5297, 0.5148, 0.5077])
tensor([0.4922, 0.5131, 0.5104, 0.4937])
tensor([0.5131, 0.5193, 0.5322, 0.5386])
tensor([0.5321, 0.5154, 0.5343, 0.5274])
tensor([0.5226, 0.5345, 0.5016, 0.5257])
tensor([0.5269, 0.5258, 0.5223, 0.5011])
tensor([0.5159, 0.5370, 0.5249, 0.5530])
tensor([0.5198, 0.5176, 0.5014, 0.4949])
tensor([0.5084, 0.5315, 0.5432, 0.5105])
tensor([0.5283, 0.5359, 0.5416, 0

/usr/local/Caskroom/miniconda/base/envs/signal-env/lib/python3.9/site-packages/torch/nn/functional.py:1806: UserWarning:

nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.



tensor([0.5238, 0.5213, 0.5145, 0.5182])
tensor([0.5095, 0.5002, 0.5017, 0.5099])
tensor([0.4948, 0.5160, 0.5414, 0.5209])
tensor([0.5202, 0.5141, 0.5158, 0.5394])
tensor([0.5256, 0.5375, 0.5067, 0.5151])
tensor([0.5126, 0.5294, 0.5325, 0.5338])
tensor([0.5133, 0.5141, 0.5064, 0.5187])
tensor([0.5287, 0.5054, 0.4878, 0.4975])
tensor([0.5000, 0.5064, 0.5305, 0.5206])
tensor([0.5144, 0.5196, 0.5338, 0.5116])
tensor([0.5051, 0.5223, 0.5119, 0.5202])
tensor([0.5250, 0.5236, 0.5021, 0.4977])
tensor([0.5092, 0.5203, 0.5031, 0.5295])
tensor([0.5493, 0.5274, 0.5396, 0.5256])
tensor([0.5334, 0.5099, 0.5296, 0.5235])
tensor([0.5248, 0.5217, 0.5212, 0.5346])
tensor([0.5345, 0.5412, 0.5252, 0.5300])
tensor([0.5120, 0.5021, 0.5069, 0.5337])
tensor([0.5253, 0.5327, 0.5311, 0.5495])
tensor([0.5636, 0.5484, 0.5378, 0.5299])
tensor([0.5337, 0.5100, 0.5023, 0.5145])
tensor([0.5182, 0.5307, 0.5184, 0.5301])
tensor([0.5403, 0.5406, 0.5492, 0.5368])
tensor([0.5152, 0.5115, 0.5083, 0.5005])
tensor([0.5148, 

After just two epochs our test loss is already starting to climb, so it's a good time to stop.

## Evaluation

Evaluating the model is straightforward. First, let's define a variant of the test function that actually returns the predictions. We also need a new DataLoader for the training set that isn't shuffled, we can visualize the training and test set predictions chronologically. Lastly, it's nice to un-standardize the predictions so they're back in their original units of micrograms per cubic meter.

In [352]:
def predict(data_loader, model):
    """Just like `test_loop` function but keep track of the outputs instead of the loss
    function.
    """
    output = torch.tensor([])
    model.eval()
    with torch.no_grad():
        for X, _ in data_loader:
            y_star = model(X)
            output = torch.cat((output, y_star), 0)
    
    return output

In [353]:
train_eval_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)

ystar_col = "Model forecast"
df_train[ystar_col] = predict(train_eval_loader, model).numpy()
df_test[ystar_col] = predict(test_loader, model).numpy()

df_out = pd.concat((df_train, df_test))[[target_feature, ystar_col]]

for c in df_out.columns:
    df_out[c] = df_out[c]

print(df_out)

                           is_replied_within_30  Model forecast
created_at                                                     
2021-09-01 00:00:00+00:00                     0        0.485213
2021-09-01 00:02:00+00:00                     1        0.497218
2021-09-01 00:04:00+00:00                     0        0.493149
2021-09-01 00:06:00+00:00                     0        0.494914
2021-09-01 00:08:00+00:00                     0        0.496587
...                                         ...             ...
2021-10-21 23:20:00+00:00                     1        0.505441
2021-10-21 23:22:00+00:00                     0        0.498711
2021-10-21 23:24:00+00:00                     1        0.495980
2021-10-21 23:26:00+00:00                     0        0.495943
2021-10-21 23:28:00+00:00                     0        0.492759

[36705 rows x 2 columns]
